// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGUEpK0wlZx9l0_Xk3NLM54SVfZoFfSnU',
    appId: '1:666001508056:web:944cb506af395e0ee079ad',
    messagingSenderId: '666001508056',
    projectId: 'freshsave-c915c',
    authDomain: 'freshsave-c915c.firebaseapp.com',
    storageBucket: 'freshsave-c915c.firebasestorage.app',
    measurementId: 'G-GGZ958DGGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7z0XmZaWwDRc2Defkgr-hpmVDd5mn75o',
    appId: '1:666001508056:android:6355b10ca3dc42cbe079ad',
    messagingSenderId: '666001508056',
    projectId: 'freshsave-c915c',
    storageBucket: 'freshsave-c915c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa6tG2JWCOchQM_dhr-QslkWBO8U1E1-c',
    appId: '1:666001508056:ios:e8826d6a6b24116be079ad',
    messagingSenderId: '666001508056',
    projectId: 'freshsave-c915c',
    storageBucket: 'freshsave-c915c.firebasestorage.app',
    iosBundleId: 'com.example.freshsaveApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa6tG2JWCOchQM_dhr-QslkWBO8U1E1-c',
    appId: '1:666001508056:ios:e8826d6a6b24116be079ad',
    messagingSenderId: '666001508056',
    projectId: 'freshsave-c915c',
    storageBucket: 'freshsave-c915c.firebasestorage.app',
    iosBundleId: 'com.example.freshsaveApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGUEpK0wlZx9l0_Xk3NLM54SVfZoFfSnU',
    appId: '1:666001508056:web:ec9e3254717e45a9e079ad',
    messagingSenderId: '666001508056',
    projectId: 'freshsave-c915c',
    authDomain: 'freshsave-c915c.firebaseapp.com',
    storageBucket: 'freshsave-c915c.firebasestorage.app',
    measurementId: 'G-7T7SB1PS7L',
  );
}
